# Generated by Django 4.2.10 on 2025-03-11 21:08

from django.db import migrations, models
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='alpha_vantage_api_key',
            field=users.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Alpha Vantage API Key'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='market_data_provider',
            field=models.CharField(choices=[('system', 'System Default'), ('yahoo', 'Yahoo Finance'), ('alpha_vantage', 'Alpha Vantage')], default='system', help_text='Select which market data provider to use', max_length=20, verbose_name='Market Data Provider'),
        ),
    ]
