version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=your-dev-secret-key
      - ALLOWED_HOSTS=localhost,127.0.0.1
      # Uncomment and set these to create a superuser on startup
      # - DJANGO_SUPERUSER_USERNAME=admin
      # - DJANGO_SUPERUSER_EMAIL=admin@example.com
      # - DJANGO_SUPERUSER_PASSWORD=adminpass
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=eqtrak
      - POSTGRES_USER=eqtrak
      - POSTGRES_PASSWORD=devpassword

volumes:
  postgres_data:
  static_volume:
  media_volume: 