# Generated by Django 4.2.10 on 2025-03-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metricvalue',
            name='metric_value_single_target',
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('portfolio__isnull', True), ('position__isnull', False), ('transaction__isnull', True)), models.Q(('portfolio__isnull', False), ('position__isnull', True), ('transaction__isnull', True)), models.Q(('portfolio__isnull', True), ('position__isnull', True), ('transaction__isnull', False)), _connector='OR'), name='metric_value_single_target'),
        ),
    ]
