# Generated by Django 4.2.10 on 2025-03-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrictype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this metric is active and available for use'),
        ),
        migrations.AddField(
            model_name='metrictype',
            name='key',
            field=models.CharField(blank=True, help_text='Unique identifier for the metric', max_length=100, null=True, unique=True),
        ),
    ]
