# Generated by Django 4.2.10 on 2025-03-09 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefinedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('latest_value', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_defined_metric', to='metrics.metricvalue')),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_defined_metrics', to='metrics.metrictype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Defined Metric',
                'verbose_name_plural': 'User Defined Metrics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'metric_type'], name='user_metric_user_id_de6270_idx'), models.Index(fields=['is_active'], name='user_metric_is_acti_b6cbf4_idx')],
            },
        ),
    ]
