# Generated by Django 5.1.6 on 2025-03-08 22:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20, verbose_name='Symbol')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('security_type', models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('mutual_fund', 'Mutual Fund'), ('bond', 'Bond'), ('crypto', 'Cryptocurrency'), ('other', 'Other')], max_length=20, verbose_name='Security Type')),
                ('exchange', models.CharField(blank=True, max_length=50, verbose_name='Exchange')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Security',
                'verbose_name_plural': 'Securities',
                'unique_together': {('symbol', 'exchange')},
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('open', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Open')),
                ('high', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='High')),
                ('low', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Low')),
                ('close', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Close')),
                ('adj_close', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Adjusted Close')),
                ('volume', models.BigIntegerField(verbose_name='Volume')),
                ('source', models.CharField(default='yahoo', max_length=50, verbose_name='Data Source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market_data.security')),
            ],
            options={
                'verbose_name': 'Price Data',
                'verbose_name_plural': 'Price Data',
                'indexes': [models.Index(fields=['security', 'date'], name='market_data_securit_0c6909_idx'), models.Index(fields=['date'], name='market_data_date_a98504_idx')],
                'unique_together': {('security', 'date')},
            },
        ),
    ]
