# Generated by Django 4.2.10 on 2025-03-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_marketdatasettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketdatasettings',
            options={'verbose_name': 'Market Data Settings', 'verbose_name_plural': 'Market Data Settings'},
        ),
    ]
